version: "3.7"
services:
  buildmap:
    image: "ghcr.io/emfcamp/buildmap:latest"
    volumes: 
      - .:/config
      - ../gis-2022:/gis-2022
      - ./output:/output
      - ./web-assets:/web
    command: "/gis-2022/map.json /config/local.conf.json"
    networks:
      - default
    depends_on:
      - db

  db:
    image: "postgis/postgis:13-3.2-alpine"
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: postgres
      PROJ_NETWORK: "ON"

  tegola:
    image: "gospatial/tegola:v0.14.0"
    ports:
      - 127.0.0.1:8888:8080
    volumes:
      - ./output:/opt/tegola_config
      - ./tegola-cache:/tmp/tegola
    command: "serve --config /opt/tegola_config/tegola.toml"
    networks:
      - web
      - default
  web:
    image: "ghcr.io/emfcamp/map-web:latest"
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - web

networks:
  web:
    name: web
