version: "3.7"

services:
  buildmap:
    build: ../buildmap
    volumes:
      - ../buildmap:/buildmap
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app

  db:
    ports:
      - 5442:5432
